---
title: "Results"
author: "David Presberger"
date: "16 Februar 2018"
output: 
  pdf_document:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plm)
library(stargazer)
library(xtable)
library(psych)
load("models.RData")
dtfull <- read.csv("DatFull.csv")
```

## Summary Statistics
```{r results='asis', warning=FALSE,echo=FALSE}
dtxtbl <- dtfull
dtxtbl$debtgdp <- dtxtbl$debtgdp^2
dtxtbl$debtext <- dtxtbl$debtext/1000000000
dtmtrx <- describe(dtxtbl[c("entryforceyear","agreementsigned","depthacc",
                            "gdp","polity","lvau_garriga","inflation",
                            "nettrade",
                            "debtext","debtgdp",
                            "underval","dunderval1",
                            "intrate","dprat1",
                            "reer","chreerplus1",
                            "crisis")], skew = F)
dtmtrx$n <- as.integer(dtmtrx$n)
dtmtrx$vars <- row.names(dtmtrx)
colnames(dtmtrx)[1:6] <- c("Variable","Observations","Mean",
                           "Standard Deviation","Minimum","Maximum")
table <- xtable(dtmtrx[-c(7,8)], latex.environments = "center",
                booktabs = TRUE)
align(table) <- "llcrrrl"
italic <- function(x){paste0('{\\emph{', x, '}}')}
print.xtable(table, include.rownames = F,
             sanitize.colnames.function = italic,
             hline.after = c(NULL,0,nrow(table)))
```

## UNDERVAL
# Difference Underval Descriptive
```{r}
hist(dtfull$dunderval1, xlim = c(-0.5,0.5), breaks = 360)
```

# Models
```{r results='asis', warning=FALSE,echo=FALSE}
stargazer(modunval1, modunval2, modunval3, modunval4, modunval5,
          title = "Effect on Undervaluation", 
          dep.var.labels = c("UNVAL+1","dUNVAL","REER"),
          type = "latex",
          keep.stat = c("rsq","n")
)
```

# Interaction Effect
```{r}
interaction_plot_continuous <- function(model, effect, moderator, interaction, varcov="default", minimum="min", maximum="max", incr="default", num_points = 50, conf=.95, mean=FALSE, median=FALSE, alph=80, rugplot=T, histogram=T, title="Marginal effects plot", xlabel="Value of moderator", ylabel="Estimated marginal coefficient"){
  
  # Define a function to make colors transparent
  makeTransparent<-function(someColor, alpha=alph){
    newColor<-col2rgb(someColor)
    apply(newColor, 2, function(curcoldata){rgb(red=curcoldata[1], green=curcoldata[2],
      blue=curcoldata[3],alpha=alpha, maxColorValue=255)})
  }
  
  # Extract Variance Covariance matrix
  if (varcov == "default"){
    covMat = vcov(model)
  }else{
    covMat = varcov
  }
  
  # Extract the data frame of the model
  mod_frame = model.frame(model)
  
  # Get coefficients of variables
  beta_1 = model$coefficients[[effect]]
  beta_3 = model$coefficients[[interaction]]
  
  # Set range of the moderator variable
  # Minimum
  if (minimum == "min"){
    min_val = min(mod_frame[[moderator]])
  }else{
    min_val = minimum
  }
  # Maximum
  if (maximum == "max"){
    max_val = max(mod_frame[[moderator]])
  }else{
    max_val = maximum
  }
  
  # Check if minimum smaller than maximum
  if (min_val > max_val){
    stop("Error: Minimum moderator value greater than maximum value.")
  }
  
  # Determine intervals between values of the moderator
  if (incr == "default"){
    increment = (max_val - min_val)/(num_points - 1)
  }else{
    increment = incr
  }
  
  # Create list of moderator values at which marginal effect is evaluated
  x_2 <- seq(from=min_val, to=max_val, by=increment)
  
  # Compute marginal effects
  delta_1 = beta_1 + beta_3*x_2
  
  # Compute variances
  var_1 = covMat[effect,effect] + (x_2^2)*covMat[interaction, interaction] + 2*x_2*covMat[effect, interaction]
  
  # Standard errors
  se_1 = sqrt(var_1)
  
  # Upper and lower confidence bounds
  z_score = qnorm(1 - ((1 - conf)/2))
  upper_bound = delta_1 + z_score*se_1
  lower_bound = delta_1 - z_score*se_1
  
  # Determine the bounds of the graphing area
  max_y = max(upper_bound)
  min_y = min(lower_bound)
  
  # Make the histogram color
  hist_col = makeTransparent("grey")
  
  # Initialize plotting window
  plot(x=c(), y=c(), ylim=c(min_y, max_y), xlim=c(min_val, max_val), xlab=xlabel, ylab=ylabel, main=title)
  
  # Plot estimated effects
  lines(y=delta_1, x=x_2)
  lines(y=upper_bound, x=x_2, lty=2)
  lines(y=lower_bound, x=x_2, lty=2)
  
  # Add a dashed horizontal line for zero
  abline(h=0, lty=3, lwd=2, col="darkgreen")
  
  # Add a vertical line at the mean
  if (mean){
    abline(v = mean(mod_frame[[moderator]]), lty=2, col="red")
  }
  
  # Add a vertical line at the median
  if (median){
    abline(v = median(mod_frame[[moderator]]), lty=3, col="blue")
  }
  
  # Add Rug plot
  if (rugplot){
    rug(mod_frame[[moderator]])
  }
  # Add Histogram (Histogram only plots when minimum and maximum are the min/max of the moderator)
  if (histogram & minimum=="min" & maximum=="max"){
    par(new=T)
    hist(mod_frame[[moderator]], axes=F, xlab="", ylab="",main="", border=hist_col, col=hist_col)
  }
}

interaction_plot_continuous(modunval3,"log1p(depthacc)","lvau_garriga","log1p(depthacc):lvau_garriga")
```


## POLICY RATES
```{r results='asis', warning=FALSE,echo=FALSE}
stargazer(modprat1,modprat2,modprat3,modprat4,modprat5,modprat6,
          title = "Effect on Policy Rates", 
          dep.var.labels = c("PRAT+1","PRAT+1","PRAT+1",
                             "dPRAT+1","dPRAT+2","dPRAT+3"),
          type = "latex",
          keep.stat = c("rsq","n")
)
```

## ROBUSTNESS

```{r results='asis', warning=FALSE,echo=FALSE}
stargazer(modrobust1,modrobust2,modrobust3,modrobust4,
          title = "Effect on Undervaluation Broken Down", 
          dep.var.labels = c("UNVALp1","UNVALnNETp","OVALp1","OVALpNETm"),
          type = "latex",
          keep.stat = c("rsq","n")
)
```

